[package]
name = "swc_optimize_barrel"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = { workspace = true }
serde = { workspace = true, features = ["derive"] }
swc_core = { workspace = true, features = [
  "base",
  "ecma_ast",
  "common"
]}